In [1]:
import torch
import lovely_tensors as lt
lt.monkey_patch()

In [2]:
t = torch.rand((1, 4, 4)) * 20 + 5
t.v

tensor[1, 4, 4] n=16 x∈[5.348, 24.190] μ=15.168 σ=5.696
tensor([[[16.1421,  8.2256, 12.9223, 18.8430],
         [20.0902, 17.2399, 24.1895, 11.8725],
         [ 9.8896, 19.2744, 16.9365,  5.3478],
         [22.7485, 17.3995,  5.6366, 15.9374]]])

In [3]:
t.size(), t.numel(), t.min(), t.max(), t.mean(), t.std()

(torch.Size([1, 4, 4]),
 16,
 tensor 5.348,
 tensor 24.190,
 tensor 15.168,
 tensor 5.696)

In [4]:
layer = torch.nn.AvgPool2d((2,2))

t2 = layer(t)
t2.v

tensor[1, 2, 2] n=4 x∈[10.965, 17.328] μ=15.168 σ=2.921 [[[15.424, 16.957], [17.328, 10.965]]]
tensor([[[15.4244, 16.9569],
         [17.3280, 10.9646]]])

In [5]:
layer = torch.nn.MaxPool2d((2,2))

t2 = layer(t)
t2.v

tensor[1, 2, 2] n=4 x∈[16.937, 24.190] μ=20.991 σ=3.192 [[[20.090, 24.190], [22.748, 16.937]]]
tensor([[[20.0902, 24.1895],
         [22.7485, 16.9365]]])

# einops

In [13]:
a = torch.arange(6).reshape(2, 3)
a.v

tensor[2, 3] i64 n=6 x∈[0, 5] μ=2.500 σ=1.871 [[0, 1, 2], [3, 4, 5]]
tensor([[0, 1, 2],
        [3, 4, 5]])

In [18]:
torch.einsum("ik -> ki", a).v

tensor[3, 2] i64 n=6 x∈[0, 5] μ=2.500 σ=1.871 [[0, 3], [1, 4], [2, 5]]
tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [21]:
torch.einsum("ij ->", a).v

tensor i64 15
tensor(15)

In [22]:
torch.einsum("ij->j", a).v

tensor[3] i64 x∈[3, 7] μ=5.000 σ=2.000 [3, 5, 7]
tensor([3, 5, 7])

In [24]:
torch.einsum("ij->i", a).v

tensor[2] i64 μ=7.500 σ=6.364 [3, 12]
tensor([ 3, 12])

In [25]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
a, b

(tensor[2, 3] i64 n=6 x∈[0, 5] μ=2.500 σ=1.871 [[0, 1, 2], [3, 4, 5]],
 tensor[3] i64 x∈[0, 2] μ=1.000 σ=1.000 [0, 1, 2])

In [29]:
torch.einsum("ij,j->i",[a, b])

tensor[2] i64 μ=9.500 σ=6.364 [5, 14]

In [30]:
a @ b

tensor[2] i64 μ=9.500 σ=6.364 [5, 14]

`torch.einsum("ij,j->i",[a, b])` is technically equivalent to `a @ b`. The former is just more readable.

In [32]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)

torch.einsum("ij,jk->ik", [a, b])

tensor[2, 5] i64 n=10 x∈[25, 118] μ=62.500 σ=35.672 [[25, 28, 31, 34, 37], [70, 82, 94, 106, 118]]

In [33]:
a @ b

tensor[2, 5] i64 n=10 x∈[25, 118] μ=62.500 σ=35.672 [[25, 28, 31, 34, 37], [70, 82, 94, 106, 118]]

`torch.einsum("ij,jk->ik", [a, b])` == `a @ b`

In [39]:
a = torch.arange(3)
b = torch.arange(3, 6)
a, b

a @ b

tensor i64 14

In [40]:
a.v, b.v

(tensor[3] i64 x∈[0, 2] μ=1.000 σ=1.000 [0, 1, 2]
 tensor([0, 1, 2]),
 tensor[3] i64 x∈[3, 5] μ=4.000 σ=1.000 [3, 4, 5]
 tensor([3, 4, 5]))

In [41]:
torch.einsum("i,i->", [a, b])

tensor i64 14

More here: https://rockt.ai/2018/04/30/einsum