In [1]:
import torch
import lovely_tensors as lt
lt.monkey_patch()

In [2]:
t = torch.rand((1, 4, 4)) * 20 + 5
t.v

tensor[1, 4, 4] n=16 x∈[5.289, 24.650] μ=12.314 σ=6.481
tensor([[[11.0658, 24.6500, 10.1457, 24.4217],
         [11.1051,  5.9737, 18.5977, 10.0164],
         [11.3962, 14.2286,  5.2887,  8.5256],
         [ 7.6007,  6.0853,  6.7507, 21.1693]]])

In [3]:
t.size(), t.numel(), t.min(), t.max(), t.mean(), t.std()

(torch.Size([1, 4, 4]),
 16,
 tensor 5.289,
 tensor 24.650,
 tensor 12.314,
 tensor 6.481)

In [4]:
layer = torch.nn.AvgPool2d((2,2))

t2 = layer(t)
t2.v

tensor[1, 2, 2] n=4 x∈[9.828, 15.795] μ=12.314 σ=2.746 [[[13.199, 15.795], [9.828, 10.434]]]
tensor([[[13.1986, 15.7954],
         [ 9.8277, 10.4336]]])

In [5]:
layer = torch.nn.MaxPool2d((2,2))

t2 = layer(t)
t2.v

tensor[1, 2, 2] n=4 x∈[14.229, 24.650] μ=21.117 σ=4.860 [[[24.650, 24.422], [14.229, 21.169]]]
tensor([[[24.6500, 24.4217],
         [14.2286, 21.1693]]])